name: CI MovieFan API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: alfre
          POSTGRES_PASSWORD: alfre123
          POSTGRES_DB: moviefan
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGPORT: ${{ secrets.PGPORT }}
      PGHOST: ${{ secrets.PGHOST }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Esperar a que Postgres esté listo
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Postgres disponible" && break
            echo "Esperando Postgres..."
            sleep 3
          done

      - name: Test de conexión a la DB
        run: |
          node -e "const pool = require('./db'); pool.query('SELECT 1').then(() => { console.log('✅ Conexión exitosa'); return pool.end(); }).catch(err => { console.error('❌ Falló la conexión'); process.exit(1); })"
